### ISSUE TITLE
Refactor the intro sentence, 'When you create a virtual server...'

### ISSUE THREAD

**Issue by cknabe** [IBM-Bluemix-Docs/vsi#15]
This sentence is hard to read quickly: 
`When you create a virtual server, you can choose from hourly or monthly billing, public (multitenancy) environment or dedicated (single-tenant) environment, and high-performance local disks or enterprise SAN storage.`

Maybe break it up into two sentences?

**Comment by mlgordon** [comment]
@cknabe Thank you for the feedback! I will break this up into a few sentences to make it easier to read and understand. Once I make the change, it will be effective immediately.
