### ISSUE TITLE
Please add Veeam

### ISSUE THREAD

**Issue by khayama** [IBM-Bluemix-Docs/vsi#20]
Please add Veeam

**Comment by stemke** [comment]
@khayama - thank you for submitting this request. Can you tell us more about what type of Veeam information you are looking for?  

We have some information about Veeam located here in our Virtualization sub-collection: https://console.bluemix.net/docs/infrastructure/virtualization/backup-your-vmware-vsphere-environment-veeam.html#backing-up-your-vmware-vsphere-environment-by-using-veeam

If you search from the Docs home page, you'll find several results as well.  Thanks again for taking the time to submit feedback and help gives us additional information to improve your experience.

**Comment by khayama** [comment]
We can use "Veeam Agent" for VSI as a backup solution.
Please describe how to use it.

Ref.
Now available: Veeam on IBM Cloud price reductions + new licensing options + free trial - IBM Cloud Blog : https://www.ibm.com/blogs/bluemix/2018/06/now-available-veeam-ibm-cloud-price-reductions-new-licensing-options-free-trial/

**Comment by stemke** [comment]
@khayama - thank you for the additional information. I see the blog reference is related to our IBM Cloud VMware solution: https://console.bluemix.net/docs/services/vmwaresolutions/services/managingveeam.html#managing-veeam-on-ibm-cloud

We will investigate this further and work to make any necessary updates.  Thank you again for the feedback. 

@jmilst - pls see this issue related to VMware solutions and connections from the VSI information.
