### ISSUE TITLE
Provisioning steps are not correct / confusing.

### ISSUE THREAD

**Issue by jamesbeltonIBM** [IBM-Bluemix-Docs/vsi#22]
I've followed both sets of numbered steps and they are not correct or are out of date.
Suggest the following is used to replace:
------
Provisioning a transient virtual server instance through the Devices icon

To provision your transient virtual server instance through the Devices icon, complete the following steps:

1.    From the IBM Cloud infrastructure customer portal, locate the Order section and click Devices.
2.    Click Virtual Server from the Catalog page
3.    Click Public Virtual Server and then click Create
4.    On the Virtual Server Order Form, under Type, select Transient from the drop down menu
5.    Complete all other relevant information for your server
6.    Review your Order Summary and check the box to agree to any Third-Party service agreements listed
7.     Click Provision
----
Provisioning a transient virtual server instance through the Devices menu

You can also provision your transient virtual server instances through the Devices menu on the main IBM Cloud infrastructure customer portal page.

1.     Click Devices > Device List.
            The Devices page displays all device types: dedicated hosts, virtual servers, bare metal servers, and NetScaler application delivery controllers—within your account.
2.     Click the Order Devices link in the upper right corner.
3.    Click Virtual Server from the Catalog page
4.    Click Public Virtual Server and then click Create
5.    On the Virtual Server Order Form, under Type, select Transient from the drop down menu
6.    Complete all other relevant information for your server
7.    Review your Order Summary and check the box to agree to any Third-Party service agreements listed
8.     Click Provision

**Comment by mlgordon** [comment]
@jamesbeltonIBM Thank you for your feedback! I'll take a look at this.

**Comment by mlgordon** [comment]
Provisioning steps have been updated! Thanks again for your feedback.
