### ISSUE TITLE
Virtual Server Steps in Table 1 need updated

### ISSUE THREAD

**Issue by SammyC4IBM** [IBM-Bluemix-Docs/vsi#23]
Instructions in the on-line doc are not right today - confusing.

Step 5 under "IBM Cloud Catalog" login set should just say "From the left-hand Nav, click "Compute" and in the main body pick the "Virtual Server" tile.

Instructions under "Customer Portal" should say to use the 'hamburger menu' to pick 'infrastructure' and follow thru from that.

Please update these pages.

**Comment by mlgordon** [comment]
Provisioning steps have been updated! Thanks again for your feedback.
