### ISSUE TITLE
FAQ's Virtual Server

### ISSUE THREAD

**Issue by stevestrutt** [IBM-Bluemix-Docs/vsi#26]
This FAQ is unclear as to what it refers to - I'm unable to connect to the virtualization API. How can I fix this? - This error generally occurs because a password is outdated. To fix this, update the root or Administrator password for the virtual server's operating system in the IBM® Cloud infrastructure customer portal.

There is no specific 'virtualisation' API on SoftLayer. The only published API is the SL API. What error this is referring to is also unclear and what problem does it resolve?

**Comment by jmilst** [comment]
removed Virt FAQ
