### ISSUE TITLE
Suspend billing feature field is in the General section not System section

### ISSUE THREAD

**Issue by kbroussard** [IBM-Bluemix-Docs/vsi#28]
Step 4 is incorrect.  The suspend billing feature field is in the General section not System section.

"4.  On the Configuration tab in the System section, you can view whether your virtual server instance supports the suspend billing feature."

https://cloud.ibm.com/docs/vsi?topic=virtual-servers-viewing-suspend-billing-feature#viewing-suspend-billing-feature
![suspendbillinggui](https://user-images.githubusercontent.com/27734582/53602665-74521d00-3b7d-11e9-8d02-54426374b06b.jpg)

**Comment by mlgordon** [comment]
@kbroussard Thank you for bringing this to our attention. The content has been updated!
