### ISSUE TITLE
IBM Cloud Docs - Bad Web Link - Page Not Found

### ISSUE THREAD

**Issue by araniolo** [IBM-Bluemix-Docs/vsi#33]
IBM Cloud Docs / IBM Cloud Virtual Servers

Page : https://cloud.ibm.com/docs/vsi?topic=virtual-servers-configuring-virtual-servers
Bad link :  "Getting started with Virtual Private Networking (VPN)"
https://cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-gettingstarted-with-virtual-private-networking

When you select the VPN link it does not open the correct web page.
 The correct url should be 
https://cloud.ibm.com/docs/infrastructure/iaas-vpn?topic=VPN-getting-started

**Comment by mlgordon** [comment]
@araniolo Just updated the link with the correct URL. Thank you for bringing this to our attention!
